docs_dir: study

site_name: metalflare
site_author: OASCI

repo_name: oasci/metalflare
repo_url: https://github.com/oasci/metalflare

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: study/.overrides
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - toc.follow
    - search.suggest

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Options need to be indented twice for some reason?
plugins:
  - search
  - autorefs
  - material-plausible
  - macros
  - table-reader
  - gen-files:
      scripts:
        - study/gen_ref_pages.py
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths: ["metalflare"]
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://matplotlib.org/stable/objects.inv
          options:
            show_source: false
            show_root_heading: false
            annotations_path: brief
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: spacy
            show_if_no_docstring: true
  - awesome-pages:
        collapse_single_pages: true
        strict: false
        order: asc
        sort_type: natural
        order_by: title
  - glightbox:
      zoomable: true
      draggable: false
      height: 80vh
      width: auto
  - blog:
      blog_dir: management/literature/
      post_dir: "{blog}/articles"
      post_date_format: medium
      post_url_date_format: yyyy
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      archive: true
      archive_name: Articles
      archive_url_format: "articles/{date}"

extra:
  generator: false
  analytics:
    provider: plausible
    domain: metalflare.oasci.org

extra_css:
  - css/base.css
  - css/colors.css
  - css/mol.css
  - https://cdn.jsdelivr.net/npm/molstar@latest/build/viewer/molstar.css

extra_javascript:
  - js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/molstar@4.4.1/build/viewer/molstar.min.js

markdown_extensions:
  - abbr
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
