[tool.poetry]
name = "metalflare"
version = "0.0.0"
description = "Investigating metal-sensing green fluorescent protein"
authors = [
    "OASCI <us@oasci.org>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-multiversion = "^0.2.4"
furo = "^2023.9.10"
sphinx-design = "^0.5.0"
sphinxcontrib-mermaid = "^0.9.2"
sphinxemoji = "^0.2.0"
sphinx-autoapi = "^3.0.0"
sphinx-autodoc-typehints = "^1.24.0"
sphinx-copybutton = "^0.5.2"
myst-parser = "^2.0.0"
sphinx-togglebutton = "^0.3.2"
sphinxcontrib-bibtex = "^2.6.1"
sphinx-inline-tabs = "^2023.4.21"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
isort = "^5.12.0"
pylint = "^3.0.1"
mypy = "^1.6.0"
mypy-extensions = "^1.0.0"
bump-my-version = "^0.11.0"

[tool.bumpversion]
current_version = "2023.10.29"
tag = true
commit = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format-jinja = "{%- if distance == 0 -%}{{ serialize_pep440(base) }}{%- else -%}{{ serialize_pep440(base, post=distance) }}{%- endif -%}"

[tool.poetry-dynamic-versioning.substitution]
patterns = [
    "(^__version__\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
]
folders = [
    { path = "02-methods/metalflare" },
]

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "poetry-dynamic-versioning>=1.0.0,<2.0.0",
]
build-backend = "poetry_dynamic_versioning.backend"

["tool.poetry.group.conda.dependencies"]
annotated-types = "^0.6.0"
appdirs = "^1.4.4"
biopython = "^1.81"
Brotli = "^1.1.0"
build = "^1.0.3"
CacheControl = "^0.13.1"
cached-property = "^1.5.2"
cachy = "^0.3.0"
certifi = "^2023.7.22"
cffi = "^1.16.0"
cfgv = "^3.3.1"
cftime = "^1.6.3"
charset-normalizer = "^3.3.2"
cleo = "^2.1.0"
click = "^8.1.7"
click-default-group = "^1.2.4"
clikit = "^0.6.2"
colorama = "^0.4.6"
conda_lock = "^2.4.2"
conda_poetry_liaison = "^0.1.2"
contourpy = "^1.2.0"
crashtest = "^0.4.1"
cryptography = "^41.0.5"
cycler = "^0.12.1"
distlib = "^0.3.7"
dulwich = "^0.21.6"
edgembar = "^0.2"
ensureconda = "^1.4.3"
fasteners = "^0.17.3"
fastjsonschema = "^2.18.1"
filelock = "^3.13.1"
fonttools = "^4.44.0"
gitdb = "^4.0.11"
GitPython = "^3.1.40"
GridDataFormats = "^1.0.2"
gsd = "^3.2.0"
h5py = "^3.10.0"
html5lib = "^1.1"
identify = "^2.5.31"
idna = "^3.4"
importlib-metadata = "^6.8.0"
installer = "^0.7.0"
"jaraco.classes" = "^3.3.0"
jeepney = "^0.8.0"
Jinja2 = "^3.1.2"
joblib = "^1.3.2"
keyring = "^24.2.0"
kiwisolver = "^1.4.5"
MarkupSafe = "^2.1.3"
matplotlib = "^3.8.1"
mda-xdrlib = "^0.2.0"
MDAnalysis = "^2.6.1"
mmcif-pdbx = "^0+untagged.16.g90d39b2.dirty"
"MMPBSA.py" = "^16.0"
mmtf-python = "^1.1.3"
more-itertools = "^10.1.0"
mrcfile = "^1.4.3"
msgpack = "^1.0.6"
munkres = "^1.1.4"
ndfes = "^1.8"
netCDF4 = "^1.6.5"
networkx = "^3.2.1"
nodeenv = "^1.8.0"
numpy = "^1.26.0"
packaging = "^23.2"
packmol-memgen = "^2023.2.24"
pandas = "^2.1.2"
ParmEd = "^4.2.2"
pastel = "^0.2.1"
patsy = "^0.5.3"
pbr = "^5.11.1"
pdb2pqr = "^3.6.1"
pdb4amber = "^22.0"
pexpect = "^4.8.0"
Pillow = "^10.1.0"
pip = "^23.3.1"
pkginfo = "^1.9.6"
platformdirs = "^3.11.0"
poetry = "^1.7.0"
poetry-core = "^1.8.1"
poetry-plugin-export = "^1.6.0"
pre-commit = "^3.5.0"
propka = "^3.5.0"
ptyprocess = "^0.7.0"
pycparser = "^2.21"
pydantic = "^2.0.3"
pydantic_core = "^2.3.0"
pyedr = "^0.7.2"
pylev = "^1.4.0"
pyMSMT = "^22.0"
pyparsing = "^3.1.1"
pyproject_hooks = "^1.0.0"
PySocks = "^1.7.1"
python-dateutil = "^2.8.2"
pytng = "^0.0.0"
pytraj = "^2.0.6"
pytz = "^2023.3.post1"
PyYAML = "^6.0.1"
rapidfuzz = "^3.5.2"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
"ruamel.yaml" = "^0.18.5"
"ruamel.yaml.clib" = "^0.2.7"
sander = "^22.0"
scikit-learn = "^1.3.2"
scipy = "^1.11.3"
seaborn = "^0.13.0"
SecretStorage = "^3.3.3"
setuptools = "^68.2.2"
shellingham = "^1.5.4"
six = "^1.16.0"
smmap = "^5.0.0"
statsmodels = "^0.14.0"
threadpoolctl = "^3.2.0"
tidynamics = "^1.1.2"
tomli = "^2.0.1"
tomli_w = "^1.0.0"
tomlkit = "^0.12.2"
toolz = "^0.12.0"
tqdm = "^4.66.1"
trove-classifiers = "^2023.10.18"
typing_extensions = "^4.8.0"
tzdata = "^2023.3"
ukkonen = "^1.0.1"
urllib3 = "^1.26.18"
virtualenv = "^20.24.6"
webencodings = "^0.5.1"
wheel = "^0.41.3"
zipp = "^3.17.0"
