
name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize conda environment
        run: make conda-create

      - name: Setup conda
        run: make conda-setup

      - name: Install conda dependencies
        run: make from-conda-lock

      - name: Install package dependencies
        run: make install

      - name: Run tests
        run: make test
